//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/DataBase/Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Code
{
    public partial class @Actions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @Actions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Actions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""d20eb55e-883e-43ea-b1dd-d164b0acdb49"",
            ""actions"": [
                {
                    ""name"": ""Push"",
                    ""type"": ""Button"",
                    ""id"": ""f9825a87-95b5-4d5d-a049-45eea345a909"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""f4c285e7-b155-445c-b510-859f1f47c62a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7eb4360a-205e-4059-abe9-19e9208e1414"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f12fa40a-7df6-49dd-a38e-db152e7eaaa1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a711c5b7-3be7-413c-9efc-30bdd1fd6a3a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40d55db9-b3be-466e-959c-20643246ee9c"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2670221f-e9cb-4808-a764-f8194eb5fa1b"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""077e7b76-5918-4f9f-88bb-9d45a5c87286"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""724b9f69-e9d5-4eaf-bff2-31e50f962553"",
            ""actions"": [
                {
                    ""name"": ""CloseTutorial"",
                    ""type"": ""Button"",
                    ""id"": ""0b0cb1d1-f2d0-4cc0-a5c2-c1b95cc8b1d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""ad11a625-31e1-4b8f-aee0-ed4b1badb9c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Store"",
                    ""type"": ""Button"",
                    ""id"": ""ed16c4c6-28be-4897-b5ef-1f73c4f0d51b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Credits"",
                    ""type"": ""Button"",
                    ""id"": ""671ab980-da59-492c-91a0-6a988777d942"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AudioSettings"",
                    ""type"": ""Button"",
                    ""id"": ""334f421b-1604-4a38-846d-43418a7c8b4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""ae1330c0-29ca-4b12-83bd-c5b07ebd11f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1d34258e-535d-42ed-861f-2aa7d8b09481"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseTutorial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77822a2e-3698-410c-b2cc-892fdc492cdc"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6c7d5bd-7be9-4df2-b615-813afd594f56"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7835941f-8450-4112-8996-73a853efe091"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Store"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5005fe2e-73cc-45ab-b3cb-9e3b3e7618bb"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Credits"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eee6850b-d2b7-419f-a6be-3fb3838e1b5e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AudioSettings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95927e88-7c87-476a-a457-3ebe20a5a209"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Push = m_Player.FindAction("Push", throwIfNotFound: true);
            m_Player_Down = m_Player.FindAction("Down", throwIfNotFound: true);
            // Menu
            m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
            m_Menu_CloseTutorial = m_Menu.FindAction("CloseTutorial", throwIfNotFound: true);
            m_Menu_Pause = m_Menu.FindAction("Pause", throwIfNotFound: true);
            m_Menu_Store = m_Menu.FindAction("Store", throwIfNotFound: true);
            m_Menu_Credits = m_Menu.FindAction("Credits", throwIfNotFound: true);
            m_Menu_AudioSettings = m_Menu.FindAction("AudioSettings", throwIfNotFound: true);
            m_Menu_Back = m_Menu.FindAction("Back", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private IPlayerActions m_PlayerActionsCallbackInterface;
        private readonly InputAction m_Player_Push;
        private readonly InputAction m_Player_Down;
        public struct PlayerActions
        {
            private @Actions m_Wrapper;
            public PlayerActions(@Actions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Push => m_Wrapper.m_Player_Push;
            public InputAction @Down => m_Wrapper.m_Player_Down;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void SetCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
                {
                    @Push.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPush;
                    @Push.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPush;
                    @Push.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPush;
                    @Down.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDown;
                    @Down.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDown;
                    @Down.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDown;
                }
                m_Wrapper.m_PlayerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Push.started += instance.OnPush;
                    @Push.performed += instance.OnPush;
                    @Push.canceled += instance.OnPush;
                    @Down.started += instance.OnDown;
                    @Down.performed += instance.OnDown;
                    @Down.canceled += instance.OnDown;
                }
            }
        }
        public PlayerActions @Player => new PlayerActions(this);

        // Menu
        private readonly InputActionMap m_Menu;
        private IMenuActions m_MenuActionsCallbackInterface;
        private readonly InputAction m_Menu_CloseTutorial;
        private readonly InputAction m_Menu_Pause;
        private readonly InputAction m_Menu_Store;
        private readonly InputAction m_Menu_Credits;
        private readonly InputAction m_Menu_AudioSettings;
        private readonly InputAction m_Menu_Back;
        public struct MenuActions
        {
            private @Actions m_Wrapper;
            public MenuActions(@Actions wrapper) { m_Wrapper = wrapper; }
            public InputAction @CloseTutorial => m_Wrapper.m_Menu_CloseTutorial;
            public InputAction @Pause => m_Wrapper.m_Menu_Pause;
            public InputAction @Store => m_Wrapper.m_Menu_Store;
            public InputAction @Credits => m_Wrapper.m_Menu_Credits;
            public InputAction @AudioSettings => m_Wrapper.m_Menu_AudioSettings;
            public InputAction @Back => m_Wrapper.m_Menu_Back;
            public InputActionMap Get() { return m_Wrapper.m_Menu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
            public void SetCallbacks(IMenuActions instance)
            {
                if (m_Wrapper.m_MenuActionsCallbackInterface != null)
                {
                    @CloseTutorial.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnCloseTutorial;
                    @CloseTutorial.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnCloseTutorial;
                    @CloseTutorial.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnCloseTutorial;
                    @Pause.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnPause;
                    @Pause.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnPause;
                    @Pause.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnPause;
                    @Store.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnStore;
                    @Store.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnStore;
                    @Store.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnStore;
                    @Credits.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnCredits;
                    @Credits.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnCredits;
                    @Credits.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnCredits;
                    @AudioSettings.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnAudioSettings;
                    @AudioSettings.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnAudioSettings;
                    @AudioSettings.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnAudioSettings;
                    @Back.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnBack;
                    @Back.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnBack;
                    @Back.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnBack;
                }
                m_Wrapper.m_MenuActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @CloseTutorial.started += instance.OnCloseTutorial;
                    @CloseTutorial.performed += instance.OnCloseTutorial;
                    @CloseTutorial.canceled += instance.OnCloseTutorial;
                    @Pause.started += instance.OnPause;
                    @Pause.performed += instance.OnPause;
                    @Pause.canceled += instance.OnPause;
                    @Store.started += instance.OnStore;
                    @Store.performed += instance.OnStore;
                    @Store.canceled += instance.OnStore;
                    @Credits.started += instance.OnCredits;
                    @Credits.performed += instance.OnCredits;
                    @Credits.canceled += instance.OnCredits;
                    @AudioSettings.started += instance.OnAudioSettings;
                    @AudioSettings.performed += instance.OnAudioSettings;
                    @AudioSettings.canceled += instance.OnAudioSettings;
                    @Back.started += instance.OnBack;
                    @Back.performed += instance.OnBack;
                    @Back.canceled += instance.OnBack;
                }
            }
        }
        public MenuActions @Menu => new MenuActions(this);
        public interface IPlayerActions
        {
            void OnPush(InputAction.CallbackContext context);
            void OnDown(InputAction.CallbackContext context);
        }
        public interface IMenuActions
        {
            void OnCloseTutorial(InputAction.CallbackContext context);
            void OnPause(InputAction.CallbackContext context);
            void OnStore(InputAction.CallbackContext context);
            void OnCredits(InputAction.CallbackContext context);
            void OnAudioSettings(InputAction.CallbackContext context);
            void OnBack(InputAction.CallbackContext context);
        }
    }
}
